const inst_info = [
  {code: "0x00", family: "Piano", instrument:"Acoustic Grand Piano"},
  {code: "0x01", family: "Piano", instrument: "Bright Acoustic Piano"},
  {code: "0x02", family: "Piano", instrument: "Electric Grand Piano"},
  {code: "0x03", family: "Piano", instrument: "Honky-tonk Piano"},
  {code: "0x04", family: "Piano", instrument: "Electric Piano 1"},
  {code: "0x05", family: "Piano", instrument: "Electric Piano 2"},
  {code: "0x06", family: "Piano", instrument: "Harpsichord"},
  {code: "0x07", family: "Piano", instrument: "Clavichord"},
  {code: "0x08", family: "Chromatic Percussion", instrument: "Celesta"},
  {code: "0x09", family: "Chromatic Percussion", instrument: "Glockenspiel"},
  {code: "0x0A", family: "Chromatic Percussion", instrument: "Music Box"},
  {code: "0x0B", family: "Chromatic Percussion", instrument: "Vibraphone"},
  {code: "0x0C", family: "Chromatic Percussion", instrument: "Marimba"},
  {code: "0x0D", family: "Chromatic Percussion", instrument: "Xylophone"},
  {code: "0x0E", family: "Chromatic Percussion", instrument: "Tubular bells"},
  {code: "0x0F", family: "Chromatic Percussion", instrument: "Dulcimer"},
  {code: "0x10", family: "Organ", instrument: "Drawbar Organ"},
  {code: "0x11", family: "Organ", instrument: "Percussive Organ"},
  {code: "0x12", family: "Organ", instrument: "Rock Organ"},
  {code: "0x13", family: "Organ", instrument: "Church Organ"},
  {code: "0x14", family: "Organ", instrument: "Reed Organ"},
  {code: "0x15", family: "Organ", instrument: "Accordion"},
  {code: "0x16", family: "Organ", instrument: "Harmonica"},
  {code: "0x17", family: "Organ", instrument: "Tango Accordion"},
  {code: "0x18", family: "Guitar", instrument: "Acoustic Guitar (nylon)"},
  {code: "0x19", family: "Guitar", instrument: "Acoustic Guitar (steel)"},
  {code: "0x1A", family: "Guitar", instrument: "Electric Guitar (jazz)"},
  {code: "0x1B", family: "Guitar", instrument: "Electric Guitar (clean)"},
  {code: "0x1C", family: "Guitar", instrument: "Electric Guitar (muted)"},
  {code: "0x1D", family: "Guitar", instrument: "Overdriven Guitar"},
  {code: "0x1E", family: "Guitar", instrument: "Distortion Guitar"},
  {code: "0x1F", family: "Guitar", instrument: "Guitar harmonics"},
  {code: "0x20", family: "Bass", instrument: "Acoustic Bass"},
  {code: "0x21", family: "Bass", instrument: "Electric Bass (finger)"},
  {code: "0x22", family: "Bass", instrument: "Electric Bass (pick)"},
  {code: "0x23", family: "Bass", instrument: "Fretless Bass"},
  {code: "0x24", family: "Bass", instrument: "Slap Bass 1"},
  {code: "0x25", family: "Bass", instrument: "Slap bass 2"},
  {code: "0x26", family: "Bass", instrument: "Synth Bass 1"},
  {code: "0x27", family: "Bass", instrument: "Synth Bass 2"},
  {code: "0x28", family: "Strings", instrument: "Violin"},
  {code: "0x29", family: "Strings", instrument: "Viola"},
  {code: "0x2A", family: "Strings", instrument: "Cello"},
  {code: "0x2B", family: "Strings", instrument: "Contrabass"},
  {code: "0x2C", family: "Strings", instrument: "Tremolo Strings"},
  {code: "0x2D", family: "Strings", instrument: "Pizzicato Strings"},
  {code: "0x2E", family: "Strings", instrument: "Orchestral Harp"},
  {code: "0x2F", family: "Strings", instrument: "Timpani"},
  {code: "0x30", family: "Ensemble", instrument: "String Ensemble 1"},
  {code: "0x31", family: "Ensemble", instrument: "String Ensemble 2"},
  {code: "0x32", family: "Ensemble", instrument: "Synth Strings 1"},
  {code: "0x33", family: "Ensemble", instrument: "Synth Strings 2"},
  {code: "0x34", family: "Ensemble", instrument: "Choir Aahs"},
  {code: "0x35", family: "Ensemble", instrument: "Voice Oohs"},
  {code: "0x36", family: "Ensemble", instrument: "Synth Voice"},
  {code: "0x37", family: "Ensemble", instrument: "Orchestra Hit"},
  {code: "0x38", family: "Brass", instrument: "Trumpet"},
  {code: "0x39", family: "Brass", instrument: "Trombone"},
  {code: "0x3A", family: "Brass", instrument: "Tuba"},
  {code: "0x3B", family: "Brass", instrument: "Muted Trombone"},
  {code: "0x3C", family: "Brass", instrument: "French Horn"},
  {code: "0x3D", family: "Brass", instrument: "Brass Section"},
  {code: "0x3E", family: "Brass", instrument: "Synth Brass 1"},
  {code: "0x3F", family: "Brass", instrument: "Synth Brass 2"},
  {code: "0x40", family: "Reed", instrument: "Soprano Sax"},
  {code: "0x41", family: "Reed", instrument: "Alto Sax"},
  {code: "0x42", family: "Reed", instrument: "Tenor Sax"},
  {code: "0x43", family: "Reed", instrument: "Baritone Sax"},
  {code: "0x44", family: "Reed", instrument: "Oboe"},
  {code: "0x45", family: "Reed", instrument: "English Horn"},
  {code: "0x46", family: "Reed", instrument: "Bassoon"},
  {code: "0x47", family: "Reed", instrument: "Clarinet"},
  {code: "0x48", family: "Pipe", instrument: "Piccolo"},
  {code: "0x49", family: "Pipe", instrument: "Flute"},
  {code: "0x4A", family: "Pipe", instrument: "Recorder"},
  {code: "0x4B", family: "Pipe", instrument: "Pan Flute"},
  {code: "0x4C", family: "Pipe", instrument: "Blown Bottle"},
  {code: "0x4D", family: "Pipe", instrument: "Shakuhachi"},
  {code: "0x4E", family: "Pipe", instrument: "Whistle"},
  {code: "0x4F", family: "Pipe", instrument: "Ocarina"},
  {code: "0x50", family: "Synth Lead", instrument: "Lead 1 (square)"},
  {code: "0x51", family: "Synth Lead", instrument: "Lead 2 (sawtooth)"},
  {code: "0x52", family: "Synth Lead", instrument: "Lead 3 (calliope)"},
  {code: "0x53", family: "Synth Lead", instrument: "Lead 4 (chiff)"},
  {code: "0x54", family: "Synth Lead", instrument: "Lead 5 (charang)"},
  {code: "0x55", family: "Synth Lead", instrument: "Lead 6 (voice)"},
  {code: "0x56", family: "Synth Lead", instrument: "Lead 7 (fifths)"},
  {code: "0x57", family: "Synth Lead", instrument: "Lead 8 (bass + lead)"},
  {code: "0x58", family: "Synth Pad", instrument: "Pad 1 (new age)"},
  {code: "0x59", family: "Synth Pad", instrument: "Pad 2 (warm)"},
  {code: "0x5A", family: "Synth Pad", instrument: "Pad 3 (polysynth)"},
  {code: "0x5B", family: "Synth Pad", instrument: "Pad 4 (choir)"},
  {code: "0x5C", family: "Synth Pad", instrument: "Pad 5 (bowed)"},
  {code: "0x5D", family: "Synth Pad", instrument: "Pad 6 (metallic)"},
  {code: "0x5E", family: "Synth Pad", instrument: "Pad 7 (halo)"},
  {code: "0x5F", family: "Synth Pad", instrument: "Pad 8 (sweep)"},
  {code: "0x60", family: "Synth Effects", instrument: "FX 1 (rain)"},
  {code: "0x61", family: "Synth Effects", instrument: "FX 2 (soundtrack)"},
  {code: "0x62", family: "Synth Effects", instrument: "FX 3 (crystal)"},
  {code: "0x63", family: "Synth Effects", instrument: "FX 4 (atmosphere)"},
  {code: "0x64", family: "Synth Effects", instrument: "FX 5 (brightness)"},
  {code: "0x65", family: "Synth Effects", instrument: "FX 6 (goblins)"},
  {code: "0x66", family: "Synth Effects", instrument: "FX 7 (echoes)"},
  {code: "0x67", family: "Synth Effects", instrument: "FX 8 (sci-fi)"},
  {code: "0x68", family: "Ethnic", instrument: "Sitar"},
  {code: "0x69", family: "Ethnic", instrument: "Banjo"},
  {code: "0x6A", family: "Ethnic", instrument: "Shamisen"},
  {code: "0x6B", family: "Ethnic", instrument: "Koto"},
  {code: "0x6C", family: "Ethnic", instrument: "Kalimba"},
  {code: "0x6D", family: "Ethnic", instrument: "Bag pipe"},
  {code: "0x6E", family: "Ethnic", instrument: "Fiddle"},
  {code: "0x6F", family: "Ethnic", instrument: "Shanai"},
  {code: "0x70", family: "Percussive", instrument: "Tinkle Bell"},
  {code: "0x71", family: "Percussive", instrument: "Agogo"},
  {code: "0x72", family: "Percussive", instrument: "Steel Drums"},
  {code: "0x73", family: "Percussive", instrument: "Woodblock"},
  {code: "0x74", family: "Percussive", instrument: "Taiko Drum"},
  {code: "0x75", family: "Percussive", instrument: "Melodic Tom"},
  {code: "0x76", family: "Percussive", instrument: "Synth Drum"},
  {code: "0x77", family: "Percussive", instrument: "Reverse Cymbal"},
  {code: "0x78", family: "Sound Effects", instrument: "Guitar Fret Noise"},
  {code: "0x79", family: "Sound Effects", instrument: "Breath Noise"},
  {code: "0x7A", family: "Sound Effects", instrument: "Seashore"},
  {code: "0x7B", family: "Sound Effects", instrument: "Bird Tweet"},
  {code: "0x7C", family: "Sound Effects", instrument: "Telephone Ring"},
  {code: "0x7D", family: "Sound Effects", instrument: "Helicopter"},
  {code: "0x7E", family: "Sound Effects", instrument: "Applause"},
  {code: "0x7F", family: "Sound Effects", instrument: "Gunshot"}
]
